### ISSUE TITLE
Can't run main.py

### ISSUE THREAD

**Issue by StrangePigeon79** [Anees-Asghar/not-a-rickroll-ascii#1]
When I try to run the file I get this error:

Traceback (most recent call last):
  File "C:\Users\gamer\not-a-rickroll-ascii\main.py", line 3, in <module>
    from pil import Image
ModuleNotFoundError: No module named 'pil'

I already installed pillow. How can I fix it?

**Comment by anees-asghar** [comment]
Hey! Pillow probably did not install successfully, since it is incompatible with newer versions of python. I have updated pillow's version in requirements.txt, should be fixed now.
